# Aldaron's Device Interface / Screen                                          #
# Copyright (c) 2017 Plop Grizzly, Jeron Lau <jeron.lau@plopgrizzly.com>       #
# Licensed under the MIT LICENSE                                               #
#                             _        _                                       #
#                            /@\——————/@\                                      #
# .———  .                   |   o    o   |     .————      .            .       #
# |   | |  .———   .———   .——.     []     .——.  |      .——    ———: ———: | .   . #
# |   | |  |   |  |   |  \   \   <##>   /   /  |      |   |    /    /  | |   | #
# |———  |  |   |  |   |   |   ¯        ¯   |   |   -- |   |   /    /   |  \ /  #
# |     |  |   |  |———    |                |   |    | |   |  /    /    |   |   #
# |     |   ———   |       |                |    ————  |   | :——— :———  |   |   #
#                 |        \              /                              __/   #
#                           ¯————————————¯                                     #
# Cargo.toml                                                                   #

################################################################################

[package]
name = "adi_screen"
version = "0.3.0"
authors = ["Jeron Aldaron Lau <jeron.lau@plopgrizzly.com>"]

################################################################################

license = "MIT"
documentation = "https://docs.rs/adi_screen"
homepage = "http://plopgrizzly.com/adi_screen"
repository = "https://github.com/plopgrizzly/adi_screen"

################################################################################

readme = "README.md"
description = """
    Aldaron's Device Interface / Screen is a library developed by Plop Grizzly
    for interfacing with a computer screen or phone screen to render graphics.
"""
keywords = [ "vulkan", "graphics", "gui", "hardware", "rendering" ]
categories = ["gui", "game-engines", "hardware-support", "multimedia::video",
	"rendering::graphics-api"]

################################################################################

exclude = ["examples/*", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", ".gitignore"]
build = "build.rs"

################################################################################

[dependencies]
afi = "^0.1"
adi_clock = { path = "/home/aldaron/plopgrizzly/devel/adi_clock" }
awi = { path = "/home/aldaron/plopgrizzly/devel/awi" }
ami = "^0.5"
adi_gpu = { path = "/home/aldaron/plopgrizzly/devel/adi_gpu" }
aci_png = "^0.3"

[dev-dependencies]
aci_ppm = "^0.2"

################################################################################
